.TH apoco(1)

.Sh NAME
.B apoco 
- automatic post-correction of (historical) OCR documents

.SH SYNOPSIS
.B apoco
.RB [OPTION]...
.RB [COMMAND]...
.RB [ARG]...

.SH DESCRIPTION
.B apoco
performes various tasks related to the automatic post-correction
of (historical) OCR documents.

.SH OPTIONS
--help Print usage statement

-l,--log-level="DEBUG|INFO" Sets the logging level (default is INFO)