// Code generated by "stringer -type StokType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SkippedShort-0]
	_ = x[SkippedShortErr-1]
	_ = x[SkippedNoCand-2]
	_ = x[SkippedNoCandErr-3]
	_ = x[SkippedLex-4]
	_ = x[FalseFriend-5]
	_ = x[SuspiciousReplacedCorrect-6]
	_ = x[InfelicitousCorrection-7]
	_ = x[SuccessfulCorrection-8]
	_ = x[DoNotCareCorrection-9]
	_ = x[SuspiciousNotReplacedCorrect-10]
	_ = x[DodgedBullet-11]
	_ = x[MissedOpportunity-12]
	_ = x[SuspiciousNotReplacedNotCorrectErr-13]
}

const _StokType_name = "SkippedShortSkippedShortErrSkippedNoCandSkippedNoCandErrSkippedLexFalseFriendSuspiciousReplacedCorrectInfelicitousCorrectionSuccessfulCorrectionDoNotCareCorrectionSuspiciousNotReplacedCorrectDodgedBulletMissedOpportunitySuspiciousNotReplacedNotCorrectErr"

var _StokType_index = [...]uint8{0, 12, 27, 40, 56, 66, 77, 102, 124, 144, 163, 191, 203, 220, 254}

func (i StokType) String() string {
	if i < 0 || i >= StokType(len(_StokType_index)-1) {
		return "StokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StokType_name[_StokType_index[i]:_StokType_index[i+1]]
}
